# **Projeto Final do Módulo Análise Exploratória de Dados**
Felipe Albanez de Oliveira  
## **Dataset**
vendas_supermercado_com_cliente.csv

## **Objetivo**
### Responder as perguntas listadas abaixo combinando Estatística Descritiva e Estatística Inferencial.  
1. Quais foram as categorias produtos mais vendidos e em quais meses eles tiveram o maior pico de vendas?  
2. Qual foi o impacto das promoções (descontos aplicados) nas vendas?
Quais produtos tiveram o maior aumento nas vendas durante as promoções? 
3. Qual a média de vendas diárias por categoria de produto?   
4. Quais produtos apresentam a maior sazonalidade nas vendas (ex.: frutas e vegetais, sorvetes)? Para responder essa pergunta considere a medida de sazonalidade dada pelo coeficiente de variação mensal dos produtos.  
5. Quais as faixas etárias contribuíram mais para as vendas totais? Para responder essa pergunta, crie uma coluna com a faixa etária, considerando: entre 18 e 35 (jovem), entre 36 e 59 (adulto) e acima de 60 anos (idoso). 
6. Qual a distribuição das vendas ao longo dos dias da semana?  
7. Como as vendas mensais se comparam antes e durante a Black Friday?  
08. Qual é o ticket médio (valor médio das vendas) por faixa etária e como ele varia entre diferentes categorias de produto?   
09. Qual é a relação entre a idade dos clientes e o valor total das compras?  
10. Comparando a semana da "Black Friday" com a do Natal, qual semana a empresa teve melhores desempenhos em 
relação à média de vendas?

---
## **Limpeza dos Dados**

### **Criação do Dataframe**

In [20]:
# importação das bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
""""
sep=';': Os dados usam ponto e vírgula para separar as colunas
decimal=",": números decimais usam vírgula
encoding='latin-1': Evita erros de leitura com acentos e caracteres da língua portuguesa.
parse_dates=['Data']) >> transforma a coluna data em datetime
"""
# caminho mac
#pasta_arquivo = "../dados/consulta_cand_2022_BRASIL.csv"

# caminho pc
#pasta_arquivo = "../Estudos/CAIXA_Verso/Módulo 02 - Análise Exploratória de Dados/vendas_supermercado_com_cliente.csv"

# caminho note trabalho
# pasta_arquivo = "/Users/cxxxxxx/OneDrive - Caixa Economica Federal/Área de Trabalho/CAIXA Verso/Projeto Final/Base de dados/consulta_cand_2022_BRASIL.csv"

# cria o dataframe lendo o arquivo .csv
# transforma a coluna data em datetime
df_vendas = pd.read_csv('vendas_supermercado_com_cliente.csv', parse_dates=['Data'])

### **Vizualização do Dataframe**

In [26]:
# vizualisa as 5 primeiras linhas do dataframe
df_vendas.head()

,Data,Produto,Categoria,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda
0,2023-01-01,Maçãs,Alimentos Frescos,16.46,10,0.0,164.60,49,2715.61
1,2023-01-01,Bananas,Alimentos Frescos,2.39,4,0.0,9.56,29,2280.15
2,2023-01-01,Laranjas,Alimentos Frescos,8.38,5,0.0,41.90,67,4419.56
3,2023-01-01,Tomates,Alimentos Frescos,2.03,15,0.0,30.45,29,3809.17
4,2023-01-01,Alface,Alimentos Frescos,37.14,14,0.0,519.96,24,1013.42

### **Conhecendo o Dataframe**

In [27]:
# informar o número de linhas e colunas
print('Shape:', df_vendas.shape)

Shape: (20075, 9)

In [ ]:
# Informações do DataFrame, incluindo o índice dtype e colunas, valores não-NA e uso de memória
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20075 entries, 0 to 20074
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Data         20075 non-null  datetime64[ns]
 1   Produto      20075 non-null  object
 2   Categoria    20075 non-null  object
 3   Preço        20075 non-null  float64
 4   Quantidade   20075 non-null  int64
 5   Desconto     20075 non-null  float64
 6   Total_Venda  20075 non-null  float64
 7   Idade        20075 non-null  int64
 8   Renda        20075 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(2), object(2)
memory usage: 1.4+ MB

##### **Resultado:** Não foram localizados faltantes/nulos

In [ ]:
# distribuição dos números
df_vendas.describe().round(2)

,Data,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda
count,20075,20075.00,20075.00,20075.00,20075.00,20075.00,20075.00
mean,2023-07-02 00:00:00,25.58,10.01,0.04,245.90,45.99,2999.03
min,2023-01-01 00:00:00,1.00,1.00,0.00,0.91,18.00,1000.38
25%,2023-04-02 00:00:00,13.26,5.00,0.00,75.60,32.00,1993.62
50%,2023-07-02 00:00:00,25.66,10.00,0.00,186.32,46.00,2998.83
75%,2023-10-01 00:00:00,37.77,15.00,0.00,370.04,60.00,4007.68
max,2023-12-31 00:00:00,49.99,19.00,0.50,949.05,74.00,4999.76
std,NaN,14.12,5.49,0.09,207.77,16.48,1159.72

In [ ]:
# incluindo apenas colunas numéricas
df_vendas.describe(include=[np.number])

,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda
count,20075.000000,20075.000000,20075.000000,20075.000000,20075.000000,20075.000000
mean,25.577109,10.007671,0.039760,245.901736,45.992827,2999.034265
std,14.115988,5.488450,0.085011,207.773694,16.482103,1159.717376
min,1.000000,1.000000,0.000000,0.910200,18.000000,1000.380000
25%,13.260000,5.000000,0.000000,75.604500,32.000000,1993.625000
50%,25.660000,10.000000,0.000000,186.320000,46.000000,2998.830000
75%,37.770000,15.000000,0.000000,370.040000,60.000000,4007.675000
max,49.990000,19.000000,0.500000,949.050000,74.000000,4999.760000

In [34]:
# incluindo apenas colunas categóricas
df_vendas.describe(include=[object])

       Produto          Categoria
count    20075              20075
unique      55                  9
top      Maçãs  Alimentos Frescos
freq       365               5475

### **Avaliando as categorizações**

In [ ]:
# vizualisação da categorias
df_vendas.columns

Index(['Data', 'Produto', 'Categoria', 'Preço', 'Quantidade', 'Desconto',
       'Total_Venda', 'Idade', 'Renda'],
      dtype='object')

In [ ]:
df_vendas['Produto'].value_counts(dropna=False)

In [ ]:
df_vendas['Categoria'].value_counts(dropna=False)

##### **Resultado:** Não foram identificados erros