# **Projeto Final do Módulo Análise Exploratória de Dados**
Felipe Albanez de Oliveira  
## **Dataset**
vendas_supermercado_com_cliente.csv

## **Objetivo**
### Responder as perguntas listadas abaixo combinando Estatística Descritiva e Estatística Inferencial.  
1. Quais foram as categorias produtos mais vendidos e em quais meses eles tiveram o maior pico de vendas?  
2. Qual foi o impacto das promoções (descontos aplicados) nas vendas?
Quais produtos tiveram o maior aumento nas vendas durante as promoções? 
3. Qual a média de vendas diárias por categoria de produto?   
4. Quais produtos apresentam a maior sazonalidade nas vendas (ex.: frutas e vegetais, sorvetes)? Para responder essa pergunta considere a medida de sazonalidade dada pelo coeficiente de variação mensal dos produtos.  
5. Quais as faixas etárias contribuíram mais para as vendas totais? Para responder essa pergunta, crie uma coluna com a faixa etária, considerando: entre 18 e 35 (jovem), entre 36 e 59 (adulto) e acima de 60 anos (idoso). 
6. Qual a distribuição das vendas ao longo dos dias da semana?  
7. Como as vendas mensais se comparam antes e durante a Black Friday?  
08. Qual é o ticket médio (valor médio das vendas) por faixa etária e como ele varia entre diferentes categorias de produto?   
09. Qual é a relação entre a idade dos clientes e o valor total das compras?  
10. Comparando a semana da "Black Friday" com a do Natal, qual semana a empresa teve melhores desempenhos em 
relação à média de vendas?

---
## **Diagnóstico Inicial**

### **Criação do Dataframe**
Importando as bibliotecas e lendo o arquivo com `read_csv`  
Transformando a coluna `Data` em datetime com `parse_date`

In [1]:
# importação das bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [91]:
""""
sep=';': Os dados usam ponto e vírgula para separar as colunas
decimal=",": números decimais usam vírgula
encoding='latin-1': Evita erros de leitura com acentos e caracteres da língua portuguesa.
parse_dates=['Data']) >> transforma a coluna data em datetime
"""
# caminho mac
#pasta_arquivo = "../dados/consulta_cand_2022_BRASIL.csv"

# caminho pc
#pasta_arquivo = "../Estudos/CAIXA_Verso/Módulo 02 - Análise Exploratória de Dados/vendas_supermercado_com_cliente.csv"

# caminho note trabalho
# pasta_arquivo = "/Users/cxxxxxx/OneDrive - Caixa Economica Federal/Área de Trabalho/CAIXA Verso/Projeto Final/Base de dados/consulta_cand_2022_BRASIL.csv"

# cria o dataframe lendo o arquivo .csv
# transforma a coluna data em datetime
df_vendas = pd.read_csv('vendas_supermercado_com_cliente.csv', parse_dates=['Data'])

### **Vizualização do Dataframe**
Métodos `head` e `tail`

In [11]:
# vizualisa as 5 primeiras linhas do dataframe
display(df_vendas.head())
# vizualisa as 5 ultimas linhas do dataframe
display(df_vendas.tail())

,Data,Produto,Categoria,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda
0,2023-01-01,Maçãs,Alimentos Frescos,16.46,10,0.0,164.60,49,2715.61
1,2023-01-01,Bananas,Alimentos Frescos,2.39,4,0.0,9.56,29,2280.15
2,2023-01-01,Laranjas,Alimentos Frescos,8.38,5,0.0,41.90,67,4419.56
3,2023-01-01,Tomates,Alimentos Frescos,2.03,15,0.0,30.45,29,3809.17
4,2023-01-01,Alface,Alimentos Frescos,37.14,14,0.0,519.96,24,1013.42

,Data,Produto,Categoria,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda
20070,2023-12-31,Produtos de higiene para pets,Pet Shop,26.62,15,0.21,315.4470,39,2475.82
20071,2023-12-31,Panelas,Utilidades Domésticas,33.00,19,0.15,532.9500,25,4766.49
20072,2023-12-31,Talheres,Utilidades Domésticas,27.60,12,0.29,235.1520,65,3367.68
20073,2023-12-31,Copos,Utilidades Domésticas,15.35,13,0.25,149.6625,42,3823.50
20074,2023-12-31,"Produtos descartáveis (pratos, copos, talheres)",Utilidades Domésticas,32.06,6,0.11,171.2004,59,3303.47

### **Conhecendo o Dataframe**
Métodos `shape` e `info`

In [4]:
# informar o número de linhas e colunas
print('Shape:', df_vendas.shape)

Shape: (20075, 9)

In [5]:
# Informações do DataFrame, incluindo o índice dtype e colunas, valores não-NA e uso de memória
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20075 entries, 0 to 20074
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Data         20075 non-null  datetime64[ns]
 1   Produto      20075 non-null  object
 2   Categoria    20075 non-null  object
 3   Preço        20075 non-null  float64
 4   Quantidade   20075 non-null  int64
 5   Desconto     20075 non-null  float64
 6   Total_Venda  20075 non-null  float64
 7   Idade        20075 non-null  int64
 8   Renda        20075 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(2), object(2)
memory usage: 1.4+ MB

### **Estatísticas Descritivas**
Método `describle` e utilização de `np.number` e `object`

In [13]:
# distribuição dos números
df_vendas.describe().round(2)

,Data,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda
count,20075,20075.00,20075.00,20075.00,20075.00,20075.00,20075.00
mean,2023-07-02 00:00:00,25.58,10.01,0.04,245.90,45.99,2999.03
min,2023-01-01 00:00:00,1.00,1.00,0.00,0.91,18.00,1000.38
25%,2023-04-02 00:00:00,13.26,5.00,0.00,75.60,32.00,1993.62
50%,2023-07-02 00:00:00,25.66,10.00,0.00,186.32,46.00,2998.83
75%,2023-10-01 00:00:00,37.77,15.00,0.00,370.04,60.00,4007.68
max,2023-12-31 00:00:00,49.99,19.00,0.50,949.05,74.00,4999.76
std,NaN,14.12,5.49,0.09,207.77,16.48,1159.72

In [14]:
# incluindo apenas colunas numéricas
df_vendas.describe(include=[np.number]).round(2)

          Preço  Quantidade  Desconto  Total_Venda     Idade     Renda
count  20075.00    20075.00  20075.00     20075.00  20075.00  20075.00
mean      25.58       10.01      0.04       245.90     45.99   2999.03
std       14.12        5.49      0.09       207.77     16.48   1159.72
min        1.00        1.00      0.00         0.91     18.00   1000.38
25%       13.26        5.00      0.00        75.60     32.00   1993.62
50%       25.66       10.00      0.00       186.32     46.00   2998.83
75%       37.77       15.00      0.00       370.04     60.00   4007.68
max       49.99       19.00      0.50       949.05     74.00   4999.76

In [7]:
# incluindo apenas colunas categóricas
df_vendas.describe(include=[object])

       Produto          Categoria
count    20075              20075
unique      55                  9
top      Maçãs  Alimentos Frescos
freq       365               5475

### **Verificando inconsistências na Categorização**

Método `value.counts` e `unique`  

> ##### Não foram localizados valores repetidos ou com erro de digitação.  

Vizualisação dos nomes de cada categoria

In [52]:
# mostra todas as colunas do dataframe
df_vendas.columns

Index(['Data', 'Produto', 'Categoria', 'Preço', 'Quantidade', 'Desconto',
       'Total_Venda', 'Idade', 'Renda'],
      dtype='object')

Frequência para cada coluna categórica: `Produto`, `Categoria`

In [53]:
# contar quantas vezes cada valor único aparece em uma coluna
df_vendas['Categoria'].value_counts(dropna=False)

Categoria
Alimentos Frescos              5475
Produtos de Mercearia          2190
Laticínios e Ovos              1825
Bebidas                        1825
Produtos de Limpeza            1825
Produtos de Higiene Pessoal    1825
Congelados                     1825
Pet Shop                       1825
Utilidades Domésticas          1460
Name: count, dtype: int64

Padronização textual (visual)

In [54]:
# unique: cria uma lista com valores únicos da coluna Produto
# sorted: ordena em ordem alfáberica para facilitar a conferência visual
print(sorted(df_vendas['Produto'].unique()))

['Alface', 'Amaciantes', 'Arroz', 'Atum', 'Azeite', 'Bananas', 'Brinquedos para pets', 'Carne bovina', 'Carne suína', 'Cenouras', 'Cervejas', 'Copos', 'Creme dental', 'Croissants', 'Desodorantes', 'Detergentes', 'Esponjas', 'Farinha', 'Feijão', 'Frango', 'Frango empanado', 'Iogurte', 'Laranjas', 'Leite', 'Limpadores multiuso', 'Macarrão', 'Manteiga', 'Maçãs', 'Ovos', 'Panelas', 'Papel higiênico', 'Petiscos', 'Pizzas congeladas', 'Pratos prontos congelados', 'Produtos de higiene para pets', 'Produtos descartáveis (pratos, copos, talheres)', 'Pão francês', 'Pão integral', 'Queijo', 'Ração para cães', 'Ração para gatos', 'Refrigerantes', 'Sabonetes', 'Sabão em pó', 'Salmão', 'Shampoos', 'Sorvetes', 'Sucos', 'Talheres', 'Tilápia', 'Tomates', 'Vegetais congelados', 'Vinhos', 'Água mineral', 'Óleo']

### **Verificando valores negativos**
Metódo `select_dtypes` e `include number`  
##### >Não foram localizados valores negativos.

Lista das colunas numéricas

In [ ]:
# seleciona somente as colunas do df com valores numéricos e retorna somente o cabeçalho
df_vendas.select_dtypes(include ='number').head(0)

Empty DataFrame
Columns: [Preço, Quantidade, Desconto, Total_Venda, Idade, Renda]
Index: []

Conferencia de valores negativos em cada coluna

In [ ]:
# verifica se existe valores negativos na coluna. Caso existir retorna o valor booleano True
# cria um df contendo somente os valores True
df_vendas[df_vendas['Preço'] < 0]

Empty DataFrame
Columns: [Data, Produto, Categoria, Preço, Quantidade, Desconto, Total_Venda, Idade, Renda]
Index: []

In [45]:
df_vendas[df_vendas['Desconto'] < 0]

Empty DataFrame
Columns: [Data, Produto, Categoria, Preço, Quantidade, Desconto, Total_Venda, Idade, Renda]
Index: []

In [46]:
df_vendas[df_vendas['Total_Venda'] < 0]

Empty DataFrame
Columns: [Data, Produto, Categoria, Preço, Quantidade, Desconto, Total_Venda, Idade, Renda]
Index: []

In [47]:
df_vendas[df_vendas['Desconto'] < 0]

Empty DataFrame
Columns: [Data, Produto, Categoria, Preço, Quantidade, Desconto, Total_Venda, Idade, Renda]
Index: []

In [49]:
df_vendas[df_vendas['Idade'] < 0]

Empty DataFrame
Columns: [Data, Produto, Categoria, Preço, Quantidade, Desconto, Total_Venda, Idade, Renda]
Index: []

In [50]:
df_vendas[df_vendas['Renda'] < 0]

Empty DataFrame
Columns: [Data, Produto, Categoria, Preço, Quantidade, Desconto, Total_Venda, Idade, Renda]
Index: []

### **Identificando Duplicados**
Método `duplicated`  
> ##### Não foram localizadas linhas duplicadas

Identificação de linhas totalmente duplicadas

In [ ]:
# verifica se existe valores duplicados. Caso existir retorna o valor booleano True
# cria um df contendo somente os valores True
df_vendas[df_vendas.duplicated()]

Empty DataFrame
Columns: [Data, Produto, Categoria, Preço, Quantidade, Desconto, Total_Venda, Idade, Renda]
Index: []

### **Localizando faltantes**
Método `isna`
> ##### Não foram localizados faltantes

In [ ]:
# mostra o total de linhas em branco para cada coluna
df_vendas.isna().sum()

Data           0
Produto        0
Categoria      0
Preço          0
Quantidade     0
Desconto       0
Total_Venda    0
Idade          0
Renda          0
dtype: int64

In [58]:
# Mostra todas as linhas da tabela que possuem algum campo em branco
df_vendas[df_vendas.isna().any(axis=1)]

Empty DataFrame
Columns: [Data, Produto, Categoria, Preço, Quantidade, Desconto, Total_Venda, Idade, Renda]
Index: []

---
## **Criação de Colunas**

### Para respondermos algumas perguntas, é necessário criarmos novas colunas para utilizarmos funções como 'Groupby'

In [93]:
# vizualisa as 5 primeiras linhas do dataframe
display(df_vendas.head(0))

Empty DataFrame
Columns: [Data, Produto, Categoria, Preço, Quantidade, Desconto, Total_Venda, Idade, Renda]
Index: []

### Coluna Mês

In [94]:
# df_vendas['Mês']: cria uma coluna no dataframe chama Mês
# dt.month: extrai da coluna data apenas o número do mês
df_vendas['Mês'] = df_vendas['Data'].dt.month
display(df_vendas.head(1))

,Data,Produto,Categoria,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda,Mês
0,2023-01-01,Maçãs,Alimentos Frescos,16.46,10,0.0,164.6,49,2715.61,1

### Coluna Dia da Semana

In [95]:
""""
A necessidade de incluir os parênteses () no final de .day_name() ocorre porque ele é um método (função interna do Pandas), 
enquanto o .month que vimos antes é apenas um atributo (uma propriedade guardada).
"""
df_vendas['Dia da Semana'] = df_vendas['Data'].dt.day_name(locale = 'pt_BR')
display(df_vendas.head(1))

,Data,Produto,Categoria,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda,Mês,Dia da Semana
0,2023-01-01,Maçãs,Alimentos Frescos,16.46,10,0.0,164.6,49,2715.61,1,Domingo

### Coluna Faixa Etária
Método `pd.cut`

In [96]:
# lista de números indicando onde cada faixa começa e termina
# Por padrão, o pd.cut() inclui o número do lado direito e exclui o do lado esquerdo (vazio, inclui].
# Por isso, no código acima, usamos o limite inicial como 17, assim o Pandas garante que quem tem 18 anos 
# cravados entrará perfeitamente na categoria 'jovem'.
idade_limite = [17, 35, 59, 150]

# lista com os nomes textuais de cada categoria
categoria = ['Jovem', 'Adulto', 'Idoso']

# cria nova coluna
df_vendas['Faixa Etária'] = pd.cut(df_vendas['Idade'], bins = idade_limite, labels = categoria)

display(df_vendas.head(1))

,Data,Produto,Categoria,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda,Mês,Dia da Semana,Faixa Etária
0,2023-01-01,Maçãs,Alimentos Frescos,16.46,10,0.0,164.6,49,2715.61,1,Domingo,Adulto

In [97]:
# confirmaçao se a categorização deu certo
display(df_vendas.loc[(df_vendas['Idade'] == 18), ['Idade', 'Faixa Etária']].head(1))

     Idade Faixa Etária
110     18        Jovem

---
## **Análise Descritiva**

#### Medidas de tendência central (média, mediana e moda)
**Variáveis numéricas:** preço, quantidade vendida, desconto, valor total da venda, idade e renda.

In [ ]:
df_vendas['Idade', 'Renda'].describe()

#### Medidas de tendência central (média, mediana e moda) e de dispersão (desvio-padrão, variância, amplitude, coeficiente de variação) para as variáveis numéricas: preço, quantidade vendida, desconto, valor total da venda, idade e renda.

---
## **Análise Exploratória**

#### 1. Quais foram as categorias produtos mais vendidos e em quais meses eles tiveram o maior pico de vendas?

In [100]:
# conferindo as colunas do dataframe
display(df_vendas.head(0))

Empty DataFrame
Columns: [Data, Produto, Categoria, Preço, Quantidade, Desconto, Total_Venda, Idade, Renda, Mês, Dia da Semana, Faixa Etária]
Index: []

In [99]:
df_gategorias = df_vendas.groupby(['Categoria'])['Total_Venda'].sum().round(2)
df_gategorias.head()

Categoria
Alimentos Frescos    1365309.46
Bebidas               454394.16
Congelados            439720.13
Laticínios e Ovos     459960.47
Pet Shop              440331.56
Name: Total_Venda, dtype: float64